-- Initialize language data
INSERT OR REPLACE INTO languages (language_code, language_name) VALUES 
  ('en', 'English'),
  ('en-US', 'English (United States)'),
  ('en-GB', 'English (United Kingdom)'),
  ('en-CA', 'English (Canada)'),
  ('en-AU', 'English (Australia)'),
  ('en-NZ', 'English (New Zealand)'),
  ('en-IE', 'English (Ireland)'),
  ('en-SG', 'English (Singapore)'),
  ('zh', 'Chinese'),
  ('zh-CN', 'Chinese (Simplified, China)'),
  ('zh-TW', 'Chinese (Traditional, Taiwan)'),
  ('zh-HK', 'Chinese (Traditional, Hong Kong)'),
  ('zh-MO', 'Chinese (Traditional, Macau)'),
  ('zh-SG', 'Chinese (Simplified, Singapore)'),
  ('fr', 'French'),
  ('fr-FR', 'French (France)'),
  ('fr-CA', 'French (Canada)'),
  ('fr-CH', 'French (Switzerland)'),
  ('fr-BE', 'French (Belgium)'),
  ('es', 'Spanish'),
  ('es-ES', 'Spanish (Spain)'),
  ('es-MX', 'Spanish (Mexico)'),
  ('es-AR', 'Spanish (Argentina)'),
  ('es-CO', 'Spanish (Colombia)'),
  ('es-CL', 'Spanish (Chile)'),
  ('es-PE', 'Spanish (Peru)'),
  ('de', 'German'),
  ('de-DE', 'German (Germany)'),
  ('de-AT', 'German (Austria)'),
  ('de-CH', 'German (Switzerland)'),
  ('ja', 'Japanese'),
  ('ja-JP', 'Japanese (Japan)'),
  ('ru', 'Russian'),
  ('ru-RU', 'Russian (Russia)'),
  ('ru-UA', 'Russian (Ukraine)'),
  ('ko', 'Korean'),
  ('ko-KR', 'Korean (South Korea)'),
  ('pt', 'Portuguese'),
  ('pt-PT', 'Portuguese (Portugal)'),
  ('pt-BR', 'Portuguese (Brazil)'),
  ('pt-MO', 'Portuguese (Macau)'),
  ('it', 'Italian'),
  ('it-IT', 'Italian (Italy)'),
  ('it-CH', 'Italian (Switzerland)'),
  ('nl', 'Dutch'),
  ('nl-NL', 'Dutch (Netherlands)'),
  ('nl-BE', 'Dutch (Belgium)'),
  ('sv', 'Swedish'),
  ('sv-SE', 'Swedish (Sweden)'),
  ('da', 'Danish'),
  ('da-DK', 'Danish (Denmark)'),
  ('fi', 'Finnish'),
  ('fi-FI', 'Finnish (Finland)'),
  ('no', 'Norwegian'),
  ('no-NO', 'Norwegian (Norway)'),
  ('pl', 'Polish'),
  ('pl-PL', 'Polish (Poland)'),
  ('tr', 'Turkish'),
  ('tr-TR', 'Turkish (Turkey)'),
  ('ar', 'Arabic'),
  ('ar-SA', 'Arabic (Saudi Arabia)'),
  ('ar-EG', 'Arabic (Egypt)'),
  ('ar-AE', 'Arabic (United Arab Emirates)'),
  ('he', 'Hebrew'),
  ('he-IL', 'Hebrew (Israel)'),
  ('cs', 'Czech'),
  ('cs-CZ', 'Czech (Czech Republic)'),
  ('el', 'Greek'),
  ('el-GR', 'Greek (Greece)'),
  ('hu', 'Hungarian'),
  ('hu-HU', 'Hungarian (Hungary)'),
  ('id', 'Indonesian'),
  ('id-ID', 'Indonesian (Indonesia)'),
  ('ms', 'Malay'),
  ('ms-MY', 'Malay (Malaysia)'),
  ('ms-SG', 'Malay (Singapore)'),
  ('th', 'Thai'),
  ('th-TH', 'Thai (Thailand)'),
  ('vi', 'Vietnamese'),
  ('vi-VN', 'Vietnamese (Vietnam)'),
  ('ta', 'Tamil'),
  ('ta-IN', 'Tamil (India)'),
  ('ta-SG', 'Tamil (Singapore)');
